# Generated by Django 5.0.2 on 2024-03-21 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="user",),
        migrations.RemoveField(model_name="facture", name="service",),
        migrations.RemoveField(model_name="service", name="client",),
        migrations.RemoveField(model_name="service", name="date_depot",),
        migrations.RemoveField(model_name="service", name="prix_total",),
        migrations.RemoveField(model_name="service", name="quantite",),
        migrations.RemoveField(model_name="service", name="user",),
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(null=True, upload_to="service"),
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField()),
                ("prix_total", models.FloatField()),
                ("date_depot", models.DateField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.client"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.service"
                    ),
                ),
            ],
            options={"db_table": "Commandes",},
        ),
        migrations.AddField(
            model_name="facture",
            name="commande",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.commande",
            ),
        ),
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addresse", models.CharField(max_length=100)),
                ("profile", models.ImageField(null=True, upload_to="profile")),
                ("couverture", models.ImageField(null=True, upload_to="couverture")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "Employers",},
        ),
    ]
