# Generated by Django 5.0.2 on 2024-03-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_client_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="addresse",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
